language: python

python:
    - "3.7"
before_install:
    - sudo apt install git gcc make
    - pip install nala==0.36.0
script:
    - make -C src test
jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - cd src/
                - bash <(curl -s https://codecov.io/bash)
