language: c
compiler: gcc
dist: bionic
python:
    - "3.7"
before_install:
    - sudo apt install git gcc make python3 python3.7 python3-pip
    - python3.7 -m pip install narmock==0.2.12
script:
    - make -C src test
jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - cd src/
                - bash <(curl -s https://codecov.io/bash)
